// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    error: string;
    load3: string;
    loader: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
